mode: "rl_melody_vs_mle_chord"
rl_melody_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/rl/rl_melody_gail_4_datasets/actor.pth"
mle_melody_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/decoder_only/decoder_only_online_melody_4_datasets/step=11000.ckpt"
mle_chord_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/decoder_only/decoder_only_online_chord/step=11000.ckpt"
num_batches: 64
dataset_name: "hooktheory"
dataset_split: "test"
prompt_steps: 64
save_dir: "logs/generated/gapt_multiscale_melody_vs_mle_chord_with_prompt"
