mode: "rl_melody_vs_rl_chord"
rl_melody_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/rl/rl_melody_gail_4_datasets/actor.pth"
rl_chord_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/rl/gapt_multiscale/actor.pth"
mle_melody_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/decoder_only/decoder_only_online_melody_4_datasets/step=11000.ckpt"
mle_chord_model_path: "/hpcwork/thes2192/realchords/logs/my_logs/decoder_only/decoder_only_online_chord/step=11000.ckpt"
num_batches: 64
save_dir: "logs/generated/gapt_multiscale_melody_vs_gapt_multiscale_chord_free_generation"
